### ISSUE TITLE
Feature to enable/disable music

### ISSUE THREAD

**Issue by skpy** [cgloeckner/pyvtt#10]
Some operators might not want to support music, for whatever reason. A simple boolean in the settings file could turn this feature off (assuming on by default), and therefore prevent the upload of MP3 files.

**Comment by cgloeckner** [comment]
this can already be done in the settings:
```
    "file_limit": {
        ...
        "num_music"  : 0
    }
```
which allows "up to 0 audio tracks" in this configuration
