### ISSUE TITLE
Implement Auth0

### ISSUE THREAD

**Issue by skpy** [cgloeckner/pyvtt#5]
Some people (i.e. me!) don't have a Google account. It'd be great to support multiple social authentication providers. Auth0 does this pretty nicely. Maybe document how to set this up for PyVTT?

**Comment by cgloeckner** [comment]
Basically, it's all about following this commit, which I recently did for sign-in-with-google:
https://github.com/cgloeckner/pyvtt/commit/49ad2fd03b6945570a6b3b433bb670ac8a33e4a4

**Comment by cgloeckner** [comment]
experimental implementation seems to work so far
