### ISSUE TITLE
Simplify logging

### ISSUE THREAD

**Issue by skpy** [cgloeckner/pyvtt#8]
Rather than store log events across different log files, I propose you log everything to one file. You can prepend each log line with a severity level (`INFO`, `WARN`, `ERR`, etc). Set a default log level (only log errors, by default) and allow operators to control log level with a command line flag (`--loglevel=INFO` would log everything of info and above).

This will reduce the number of open file handles, and simplify log cleanup.

Also, consider a `--stdout` flag that logs everything to standard out, and avoids writing to a log file at all. In Docker environments, this is preferred.

**Comment by cgloeckner** [comment]
Thanks.

Should be implemented with the last two commits
- `--no-logs` forces writing to `stdout` without creating logfiles
- `--loglevel=<LEVEL>` limits what's actually logged
